# Generated by Django 5.0.1 on 2024-01-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=40)),
                ('deporte', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='calzado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('talla', models.IntegerField()),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='indumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('talla', models.IntegerField()),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
    ]
